#!/usr/bin/env python3
"""
Stage 8: KNOWLEDGE GRAPH (deterministic, no LLM)
================================================

Turns the pipeline's artifacts into a queryable knowledge graph, and provides a
plain-English interface over it that works with or without Neo4j installed.

    python .claude/scripts/08_graph.py
    python .claude/scripts/08_graph.py --ask "what breaks if I change ACCOUNTS.BALANCE"
    python .claude/scripts/08_graph.py --list-questions

WHY THIS AGENT WAS REDESIGNED
-----------------------------
The predecessor exported 5 node types and 7 relationship types from 4 of the 7
upstream artifacts. Measured gaps:

  - no Column node, so column-level impact analysis — the single best reason to
    put this in a graph — was impossible
  - no Statement node, so the exact statement_id provenance the pipeline works
    hard to preserve was flattened to "somewhere in this procedure"
  - Agents 4, 6 and 7 were never opened: no complexity, shape, transaction
    behaviour, states or gaps
  - thin properties: objects carried only type/file_id/parse_status, so nothing
    could be ranked or filtered
  - no query interface at all, and a graph nobody knows how to query is a graph
    nobody uses

DESIGN
------
1.  ONE MODEL, TWO VIEWS. `lib_graph_model` builds an in-memory property graph;
    the CSV/Cypher export and the question interface are both views over it, so
    a locally-answered question and the same question in Neo4j cannot disagree.

2.  COLUMN AND STATEMENT ARE NODES. Property-graph practice says a thing with
    several independent relationships must be a node. A Column is read, written,
    constrained and indexed; a Statement carries control flow and rule
    provenance. Making them properties would make the interesting questions
    unaskable.

3.  A CODE PROPERTY GRAPH LAYER. Yamaguchi et al. (IEEE S&P 2014) showed that
    joining AST, control flow and data dependence into one graph answers
    questions none of them answers alone. We already hold all three.

4.  CONCEPTS AND CONSTRAINTS, after jQAssistant. The export ships derived-view
    Cypher (concepts) and validation Cypher that should return nothing
    (constraints), so an analyst can extend the graph without touching this
    extractor.

5.  DETERMINISTIC ENGLISH. Questions are matched against a named intent
    catalogue, never generated by a model. An unmatched question is reported as
    a miss with a list of what IS supported. Total precision, imperfect recall —
    the correct trade when a wrong impact-analysis answer is worse than none.

6.  DECLARED BLIND SPOTS. The impact-analysis literature is unanimous that no
    automated approach is complete. Dynamic SQL, external callers, unresolved
    calls and trigger side effects are exported as BlindSpot nodes rather than
    left as a silent absence.

This agent remains OPTIONAL: no other stage depends on it, and the JSON
artifacts stay the pipeline's source of truth.

DESIGN REFERENCES
-----------------
  Yamaguchi, Golde, Arp & Rieck (2014)  Code Property Graphs, IEEE S&P
  jQAssistant                            scan -> graph -> concepts + constraints
  Lehnert, A review of software change impact analysis
                                         no automated approach is complete
  CAST Imaging / Thoughtworks CodeConcise
                                         industry precedent for a Neo4j knowledge base
  Neo4j property-graph modelling guidance
                                         node vs relationship vs property
"""

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib_business_language import humanise, object_title, entity_title  # noqa: E402
from lib_graph_model import build_graph  # noqa: E402
from lib_graph_language import ask, INTENTS  # noqa: E402

DESIGN_REFERENCES = [
    {"work": "Yamaguchi, Golde, Arp & Rieck (2014), Code Property Graphs, IEEE S&P",
     "applied": "Statement nodes joined by control-flow and dependence edges, so "
                "queries can span syntax, flow and data dependence at once."},
    {"work": "jQAssistant (scan -> Neo4j -> concepts + constraints)",
     "applied": "The export ships derived-view Cypher and validation Cypher so the "
                "graph can be extended without changing the extractor."},
    {"work": "Lehnert, A review of software change impact analysis",
     "applied": "Blind spots are exported as nodes; no automated impact analysis is "
                "complete and the graph says so."},
    {"work": "Neo4j property-graph modelling guidance",
     "applied": "Column, Statement and Parameter are nodes because each takes part in "
                "several independent relationships; relationship properties minimised."},
]


def generate_run_version() -> str:
    now = datetime.now(timezone.utc)
    return now.strftime("%Y-%m-%dT%H.%M.%S.") + f"{now.microsecond // 1000:03d}Z"


def load_run(root: str, run: str, filename: str):
    root_path = Path(root)
    if run == "latest":
        rv = json.loads((root_path / "latest.json").read_text(encoding="utf-8"))["run_version"]
    else:
        rv = run
    return json.loads((root_path / rv / filename).read_text(encoding="utf-8")), root_path / rv


def optional(root, run, filename):
    try:
        return load_run(root, run, filename)
    except (FileNotFoundError, KeyError, json.JSONDecodeError):
        return {}, None


def collect_artifacts(args) -> dict:
    inv, _ = optional(args.inventory_root, args.run, "inventory-artifact.json")
    parser, proot = load_run(args.parser_root, args.run, "parser_artifact.json")
    data, _ = optional(args.data_root, args.run, "data_artifact.json")
    logic, lroot = optional(args.logic_root, args.run, "logic_artifact.json")
    rules, _ = optional(args.rules_root, args.run, "rules_artifact.json")
    diagrams, _ = optional(args.diagram_root, args.run, "diagrams_artifact.json")
    brd, _ = optional(args.report_root, args.run, "brd_index.json")

    parser_records = {}
    for oid, rel in (parser.get("object_index") or {}).items():
        p = proot / rel
        if p.exists():
            parser_records[oid] = json.loads(p.read_text(encoding="utf-8"))
    logic_records = {}
    for oid, rel in (logic.get("object_index") or {}).items():
        p = (lroot / rel) if lroot else None
        if p and p.exists():
            logic_records[oid] = json.loads(p.read_text(encoding="utf-8"))

    return {"inventory": inv, "parser": parser, "data": data, "logic": logic,
            "rules": rules, "diagrams": diagrams, "brd_index": brd,
            "parser_records": parser_records, "logic_records": logic_records}


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

def cypher_value(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


KEY_PROPERTY = {
    "File": "file_id", "Object": "object_id", "Parameter": "parameter_id",
    "Statement": "statement_id", "Table": "table", "Column": "column_id",
    "Index": "index", "Sequence": "sequence", "BusinessRule": "rule_id",
    "RuleSet": "rule_set_id", "State": "state_id", "Gap": "gap_id",
    "BlindSpot": "blind_spot",
}


def write_export(graph, run_dir: Path) -> dict:
    nodes_dir, rels_dir = run_dir / "nodes", run_dir / "rels"
    nodes_dir.mkdir(parents=True, exist_ok=True)
    rels_dir.mkdir(parents=True, exist_ok=True)

    lines = ["// Generated by Stage 8. MERGE throughout, so re-running is safe.",
             "// Load order matters: nodes first, then relationships.", ""]

    # Uniqueness constraints double as the indexes the MERGEs need.
    for label, keyprop in KEY_PROPERTY.items():
        if graph.nodes.get(label):
            lines.append(f"CREATE CONSTRAINT {label.lower()}_key IF NOT EXISTS "
                         f"FOR (n:{label}) REQUIRE n.{keyprop} IS UNIQUE;")
    lines.append("")

    for label, bucket in sorted(graph.nodes.items()):
        if not bucket:
            continue
        keyprop = KEY_PROPERTY.get(label, "id")
        prop_names = sorted({k for props in bucket.values() for k in props})
        with (nodes_dir / f"{label}.csv").open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow([keyprop] + prop_names)
            for key, props in sorted(bucket.items()):
                w.writerow([key] + [props.get(p, "") for p in prop_names])
        lines.append(f"// ---- {label} ({len(bucket)}) ----")
        for key, props in sorted(bucket.items()):
            assigns = ", ".join(f"n.{p} = {cypher_value(props[p])}" for p in prop_names
                                if props.get(p) is not None)
            stmt = f"MERGE (n:{label} {{{keyprop}: {cypher_value(key)}}})"
            lines.append(stmt + (f" SET {assigns};" if assigns else ";"))
        lines.append("")

    by_type = {}
    for rtype, fl, fk, tl, tk, props in graph.rels:
        by_type.setdefault(rtype, []).append((fl, fk, tl, tk, props))
    for rtype, items in sorted(by_type.items()):
        with (rels_dir / f"{rtype}.csv").open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["from_label", "from_key", "to_label", "to_key", "properties"])
            for fl, fk, tl, tk, props in items:
                w.writerow([fl, fk, tl, tk, json.dumps(props) if props else ""])
        lines.append(f"// ---- {rtype} ({len(items)}) ----")
        for fl, fk, tl, tk, props in items:
            fkp, tkp = KEY_PROPERTY.get(fl, "id"), KEY_PROPERTY.get(tl, "id")
            setter = ""
            if props:
                setter = " SET " + ", ".join(f"r.{k} = {cypher_value(v)}"
                                             for k, v in props.items())
            lines.append(
                f"MATCH (a:{fl} {{{fkp}: {cypher_value(fk)}}}), "
                f"(b:{tl} {{{tkp}: {cypher_value(tk)}}}) "
                f"MERGE (a)-[r:{rtype}]->(b){setter};")
        lines.append("")

    (run_dir / "import.cypher").write_text("\n".join(lines), encoding="utf-8")
    node_counts, rel_counts = graph.counts()
    return {"nodes": node_counts, "relationships": rel_counts}


CONCEPTS = [
    ("Hot column", "A column read or written by more than two program units — change last.",
     """MATCH (o:Object)-[:READS_COLUMN|WRITES_COLUMN]->(c:Column)
WITH c, count(DISTINCT o) AS units WHERE units > 2
SET c:HotColumn SET c.dependent_units = units RETURN c.column_id, units;"""),
    ("Rule-bearing statement", "A statement that implements at least one business rule.",
     """MATCH (br:BusinessRule)-[:IMPLEMENTED_AT]->(s:Statement)
SET s:RuleBearing RETURN s.statement_id, collect(br.rule_id);"""),
    ("Write path", "Statements on a control-flow path that ends in a write.",
     """MATCH p = (s:Statement)-[:FOLLOWS|BRANCHES_TO*1..10]->(w:Statement)
WHERE w.type IN ['UPDATE','INSERT','DELETE','MERGE']
RETURN DISTINCT s.statement_id, w.type, w.line;"""),
]

CONSTRAINTS = [
    ("Every rule traces to source",
     "A rule with no program unit and no table cannot be verified.",
     """MATCH (br:BusinessRule)
WHERE NOT (br)-[:ENFORCED_IN]->() AND NOT (br)-[:CONSTRAINS_TABLE]->()
RETURN br.rule_id;"""),
    ("No orphan columns in rules",
     "A rule constraining a column that does not exist indicates a join error.",
     """MATCH (br:BusinessRule)-[:CONSTRAINS]->(c:Column)
WHERE NOT (:Table)-[:HAS_COLUMN]->(c) RETURN br.rule_id, c.column_id;"""),
    ("Unenforced constraints are visible",
     "Any rule the database does not enforce must be flagged for review.",
     """MATCH (br:BusinessRule) WHERE br.is_enforced = false AND br.needs_review = false
RETURN br.rule_id, br.name;"""),
]


def write_docs(run_dir: Path, stats: dict, upstream: dict) -> None:
    n, r = stats["nodes"], stats["relationships"]
    lines = [
        "# Knowledge Graph — import and query guide", "",
        "Generated deterministically from the pipeline artifacts. No language model "
        "produced any node, relationship or query in this export.", "",
        "## What is in it", "",
        "| Node | Count |", "|---|---|",
        *[f"| `{k}` | {v} |" for k, v in n.items()], "",
        "| Relationship | Count |", "|---|---|",
        *[f"| `{k}` | {v} |" for k, v in r.items()], "",
        "## Loading it", "",
        "**Option A — Neo4j Browser or cypher-shell.** Run `import.cypher` top to "
        "bottom. It uses `MERGE` throughout, so re-running is safe and idempotent.", "",
        "```bash", "cat import.cypher | cypher-shell -u neo4j -p <password>", "```", "",
        "**Option B — CSV.** `nodes/` and `rels/` hold one file per label and "
        "relationship type, for `LOAD CSV` or the admin importer.", "",
        "**Option C — no Neo4j at all.** Ask questions directly against the "
        "artifacts:", "",
        "```bash",
        'python .claude/scripts/08_graph.py --ask "what breaks if I change ACCOUNTS.BALANCE"',
        "python .claude/scripts/08_graph.py --list-questions", "```", "",
        "The local answer and the Neo4j answer come from the same model, so they "
        "cannot disagree.", "",
        "## Questions this graph answers", "",
    ]
    for i in INTENTS:
        lines += [f"### {i.question}", "", "```cypher", i.cypher.strip(), "```", ""]

    lines += ["## Concepts — derived views", "",
              "Run these after loading to enrich the graph. They add labels and "
              "properties rather than new facts, so they are safe to re-run.", ""]
    for name, why, q in CONCEPTS:
        lines += [f"### {name}", "", why, "", "```cypher", q.strip(), "```", ""]

    lines += ["## Constraints — these should return nothing", "",
              "Each query below is a validation. A non-empty result is a defect in the "
              "pipeline or a genuine finding about the codebase.", ""]
    for name, why, q in CONSTRAINTS:
        lines += [f"### {name}", "", why, "", "```cypher", q.strip(), "```", ""]

    lines += ["## What this graph cannot see", "",
              "No automated dependency analysis is complete. These limits are exported "
              "as `BlindSpot` nodes so they are queryable rather than assumed away:", "",
              "```cypher", "MATCH (b:BlindSpot) RETURN b.blind_spot, b.detail;", "```", "",
              "Treat the graph as a strong lower bound on dependencies, never an upper "
              "bound. Human validation remains necessary.", "",
              "## Provenance", "", "| Setting | Value |", "|---|---|",
              *[f"| {k} | `{v}` |" for k, v in upstream.items() if v], ""]
    (run_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def render_answer(res: dict) -> str:
    if not res.get("ok"):
        out = [f"Could not answer: {res['reason']}", "", "This interface answers:"]
        out += [f"  - {s}" for s in res.get("suggestions", [])]
        return "\n".join(out)
    out = [f"Question type : {res['question']}", f"Subject       : {res['subject']}",
           f"Results       : {res['row_count']}", ""]
    if res["rows"]:
        widths = [max([len(str(h))] + [len(str(r[i])) for r in res["rows"]])
                  for i, h in enumerate(res["header"])]
        out.append("  " + "  ".join(str(h).ljust(widths[i])
                                    for i, h in enumerate(res["header"])))
        out.append("  " + "  ".join("-" * w for w in widths))
        for row in res["rows"]:
            out.append("  " + "  ".join(str(c).ljust(widths[i]) for i, c in enumerate(row)))
    else:
        out.append("  (nothing found — this is a real answer, not a failure)")
    out += ["", "Equivalent Cypher:", ""]
    out += ["  " + l for l in res["cypher"].strip().splitlines()]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description="Stage 8: knowledge graph export and query")
    ap.add_argument("--inventory-root", default="output/inventory")
    ap.add_argument("--parser-root", default="output/parser")
    ap.add_argument("--data-root", default="output/data")
    ap.add_argument("--logic-root", default="output/logic")
    ap.add_argument("--rules-root", default="output/rules")
    ap.add_argument("--diagram-root", default="output/diagram")
    ap.add_argument("--report-root", default="output/final_report")
    ap.add_argument("--run", default="latest")
    ap.add_argument("--output-root", default="output/graph")
    ap.add_argument("--output", default=None)
    ap.add_argument("--ask", default=None, help="Ask a question in plain English.")
    ap.add_argument("--list-questions", action="store_true")
    ap.add_argument("--json", action="store_true", help="Machine-readable answer.")
    args = ap.parse_args()

    if args.list_questions:
        print("Questions this interface answers:\n")
        for i in INTENTS:
            print(f"  {i.question}")
        print("\nName entities exactly, e.g. ACCOUNTS.BALANCE, SP_TRANSFER_FUNDS, BR-014.")
        return

    graph = build_graph(collect_artifacts(args), humanise, object_title, entity_title)

    if args.ask:
        res = ask(graph, args.ask)
        print(json.dumps(res, indent=2, default=str) if args.json else render_answer(res))
        sys.exit(0 if res.get("ok") else 2)

    versioned = args.output is None
    run_version = generate_run_version()
    run_dir = Path(args.output_root) / run_version if versioned else Path(args.output)
    run_dir.mkdir(parents=True, exist_ok=True)

    stats = write_export(graph, run_dir)
    upstream = {"run_selector": args.run}
    write_docs(run_dir, stats, upstream)

    artifact = {
        "pipeline_stage": "8_graph", "schema_version": "2.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "upstream": upstream, "design_references": DESIGN_REFERENCES,
        "stats": stats,
        "supported_questions": [{"intent": i.name, "question": i.question} for i in INTENTS],
        "concepts": [{"name": n, "purpose": w} for n, w, _ in CONCEPTS],
        "constraints": [{"name": n, "purpose": w} for n, w, _ in CONSTRAINTS],
        "blind_spots": [{"kind": k, "detail": p.get("detail")}
                        for k, p in graph.nodes.get("BlindSpot", {}).items()],
    }
    (run_dir / "graph_artifact.json").write_text(
        json.dumps(artifact, indent=2, ensure_ascii=False), encoding="utf-8")

    if versioned:
        (run_dir / "run_meta.json").write_text(json.dumps(
            {"stage": "8_graph", "run_version": run_version, "status": "success",
             "generated_at": artifact["generated_at"], "stats": stats}, indent=2),
            encoding="utf-8")
        (Path(args.output_root) / "latest.json").write_text(json.dumps(
            {"run_version": run_version, "path": f"{run_version}/graph_artifact.json",
             "updated_at": artifact["generated_at"]}, indent=2), encoding="utf-8")

    print("=== Knowledge Graph Complete ===")
    print(f"Nodes         : {sum(stats['nodes'].values())} across {len(stats['nodes'])} labels")
    for k, v in stats["nodes"].items():
        print(f"    {k:<14}{v}")
    print(f"Relationships : {sum(stats['relationships'].values())} across "
          f"{len(stats['relationships'])} types")
    for k, v in stats["relationships"].items():
        print(f"    {k:<20}{v}")
    print(f"Questions     : {len(INTENTS)} supported")
    print(f"Blind spots   : {len(artifact['blind_spots'])} declared")
    print(f"Output        : {run_dir / 'graph_artifact.json'}")
    print("================================")


if __name__ == "__main__":
    main()
